apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-interface
  labels: 
    app: dev
spec:
  selector:
    matchLabels:
      app: client-interface
  template:
    metadata:
      labels:
        app: client-interface
    spec:
      containers:
      - name: client-interface
        image: docker.io/ocfcloud/client-interface:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: 200m
        env:
        - name: CACHE_URI
          valueFrom:
            configMapKeyRef:
              name: registry-configmap
              key: CACHE_URI
        - name: CACHE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: registry-configmap
              key: CACHE_PASSWORD
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: registry-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom: 
            configMapKeyRef:
              name: registry-configmap
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: registry-configmap
              key: DB_NAME
        - name: DB_URI
          valueFrom:
            configMapKeyRef:
              name: registry-configmap
              key: DB_URI

        
      